services:
  - type: web
    name: chatgpt-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: test_database
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        # will be updated automatically after frontend deploy
        value: https://REPLACE_WITH_FRONTEND

  - type: static_site
    name: chatgpt-frontend
    env: static
    rootDir: frontend
    buildCommand: yarn && yarn build
    staticPublishPath: build
    plan: free
    autoDeploy: true
    envVars:
      - key: REACT_APP_BACKEND_URL
        # when both services exist on Render, set this to the backend URL
        value: https://REPLACE_WITH_BACKEND